In [1]:
#Тапсырма 1: Деректердің Орташа Мәнін Табу (Статистика)
import numpy as np
# Тапсырма 1-ді орындау үшін кодты осы жерге енгізіңіз
scores = np.array([75, 82, 68, 91, 79])

# Орташа мәнді есептеу
average_score = np.mean(scores)
average_score



np.float64(79.0)

In [2]:
#Тапсырма 2: Екі Векторды Қосу (Сызықтық Алгебра)
import numpy as np
# Тапсырма 2-ні орындау үшін кодты осы жерге енгізіңіз
A = np.array([1.5, 2.0, 0.5])
B = np.array([3.0, 1.0, 2.5])

# Векторларды қосу
C = A + B

C


array([4.5, 3. , 3. ])

In [9]:
#Тапсырма 3: Скалярлық Көбейту (Сызықтық Алгебра)
import numpy as np
v = np.array([2, -1, 5])
scalar = 3

# Скалярлық көбейтуді орындау
u = scalar * v

u


array([ 6, -3, 15])

In [10]:
#Тапсырма 4: Жай Ықтималдық (Ықтималдықтар Теориясы)
# Қажетті кітапхана: Ештеңе қажет емес (таза арифметика)
total_points = 100
correctly_classified = 92

# Дұрыс жіктелу ықтималдығын есептеу
probability_correct = correctly_classified / total_points

probability_correct


0.92

In [7]:
#Тапсырма 5: Min-Max Нормализациясы (Деректерді Өңдеу)
from sklearn.preprocessing import MinMaxScaler
import numpy as np

data_points = np.array([10, 20, 50, 40, 30]).reshape(-1, 1)

# MinMaxScaler-ді инициализациялау
scaler = MinMaxScaler(feature_range=(0, 1))

# Деректерді түрлендіру
data_normalized = scaler.fit_transform(data_points)

data_normalized


array([[0.  ],
       [0.25],
       [1.  ],
       [0.75],
       [0.5 ]])