In [1]:
import numpy as np

# 1 тапсырма 3x3 өлшемді екі матрица құру
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Қосындысын табу
sum_matrix = A + B

# Айырмасын табу
diff_matrix = A - B

# Көбейтіндісін табу (матрицалық көбейту)
prod_matrix = np.dot(A, B)

# Нәтижелерді шығару
print("Матрицалардың қосындысы:\n", sum_matrix)
print("\nМатрицалардың айырмасы:\n", diff_matrix)
print("\nМатрицалардың көбейтіндісі:\n", prod_matrix)


Матрицалардың қосындысы:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

Матрицалардың айырмасы:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Матрицалардың көбейтіндісі:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [3]:
#2 Тапсырма
import numpy as np

# 3 өлшемді екі вектор құру
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# Скаляр көбейтіндісін табу
dot_product = np.dot(v1, v2)

# Векторлардың ұзындықтарын табу
norm_v1 = np.linalg.norm(v1)
norm_v2 = np.linalg.norm(v2)

# Екі вектор арасындағы бұрыш (радианда)
cos_theta = dot_product / (norm_v1 * norm_v2)
theta_rad = np.arccos(cos_theta)

# Радианды градусқа айналдыру
theta_deg = np.degrees(theta_rad)

# Нәтижелерді шығару
print("Скаляр көбейтіндісі:", dot_product)
print("Екі вектор арасындағы бұрыш (радиан):", theta_rad)
print("Екі вектор арасындағы бұрыш (градус):", theta_deg)


Скаляр көбейтіндісі: 32
Екі вектор арасындағы бұрыш (радиан): 0.2257261285527342
Екі вектор арасындағы бұрыш (градус): 12.933154491899135


In [4]:

# 3. тапсырма Матрицаның детерминанты, кері матрицасы және өз мәндері
# ------------------------------
# Мысал матрица
C = np.array([[2, 1, 3],
              [0, 1, 4],
              [5, 2, 1]])

# Детерминант
det_C = np.linalg.det(C)
print("\nМатрицаның детерминанты:", det_C)

# Кері матрица (егер детерминант 0 болмаса ғана)
if det_C != 0:
    inv_C = np.linalg.inv(C)
    print("\nКері матрицасы:\n", inv_C)
else:
    print("\nКері матрица жоқ (детерминант 0)")

# Өз мәндері (eigenvalues)
eigenvalues = np.linalg.eigvals(C)
print("\nМатрицаның өз мәндері:", eigenvalues)


Матрицалардың қосындысы:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

Матрицалардың айырмасы:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Матрицалардың көбейтіндісі:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Векторлардың скаляр көбейтіндісі: 32
Екі вектор арасындағы бұрыш (радиан): 0.2257261285527342
Екі вектор арасындағы бұрыш (градус): 12.933154491899135

Матрицаның детерминанты: -9.000000000000002

Кері матрицасы:
 [[ 0.77777778 -0.55555556 -0.11111111]
 [-2.22222222  1.44444444  0.88888889]
 [ 0.55555556 -0.11111111 -0.22222222]]

Матрицаның өз мәндері: [ 6.54138127 -3.          0.45861873]


In [6]:
#4 тапсырма
import numpy as np

# ------------------------------
# 1. 1000 элементтік кездейсоқ үлгі
# ------------------------------
# np.random.randn(n) стандартты нормал үлестіру бойынша n кездейсоқ сандар шығарады
sample = np.random.randn(1000)

# ------------------------------
# 2. Орташа мән (mean)
# ------------------------------
# np.mean() функциясы элементтердің орташа мәнін есептейді
mean_value = np.mean(sample)
print("Орташа мән:", mean_value)

# ------------------------------
# 3. Дисперсия (variance)
# ------------------------------
# np.var() функциясы үлгінің дисперсиясын есептейді
variance_value = np.var(sample)
print("Дисперсия:", variance_value)

# ------------------------------
# 4. Стандартты ауытқу (standard deviation)
# ------------------------------
# np.std() функциясы стандартты ауытқуды есептейді
std_dev = np.std(sample)
print("Стандартты ауытқу:", std_dev)


Орташа мән: -0.01104804806749314
Дисперсия: 1.0007114673945765
Стандартты ауытқу: 1.000355670446555


In [7]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# ------------------------------
# 1. Берілген тізім
# ------------------------------
data = np.array([5, 10, 15, 20, 25]).reshape(-1, 1)  # MinMaxScaler үшін 2D массив қажет

# ------------------------------
# 2. Min-Max нормализациясы
# ------------------------------
# Формула: X_norm = (X - X_min) / (X_max - X_min)
scaler = MinMaxScaler()
data_minmax = scaler.fit_transform(data)
print("Min-Max нормализациясы:\n", data_minmax.flatten())  # flatten() тек 1D шығару үшін

# ------------------------------
# 3. Z-score нормализациясы (стандартизация)
# ------------------------------
# Формула: Z = (X - mean) / std
mean = np.mean(data)
std = np.std(data)
data_zscore = (data - mean) / std
print("\nZ-score нормализациясы:\n", data_zscore.flatten())


Min-Max нормализациясы:
 [0.   0.25 0.5  0.75 1.  ]

Z-score нормализациясы:
 [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
