In [ ]:
# # Есеп 1.1: Класс құру
class Kitap:
    def __init__(self, atau, avtory):
        self.atau = atau
        self.avtory = avtory

    def kitap_turaly_malimet(self):
        print(f"Кітап: {self.atau}, Авторы: {self.avtory}")

# Нысан (объект) жасау
meni_kitap = Kitap("Үш мушкетер", "А. Дюма")

# Әдісті шақыру
meni_kitap.kitap_turaly_malimet()


Кітап: Үш мушкетер, Авторы: А. Дюма


In [ ]:
import numpy as np

# Бір өлшемді массив
arr_a = np.arange(1, 10)  # 1-ден 9-ға дейін
print("arr_a:", arr_a)
print("Өлшемі:", arr_a.shape)
print("Деректер түрі:", arr_a.dtype)
print()

# Екі өлшемді массив (3x3)
arr_b = np.arange(1, 10).reshape(3, 3)
print("arr_b:\n", arr_b)
print("Өлшемі:", arr_b.shape)
print("Деректер түрі:", arr_b.dtype)


arr_a: [1 2 3 4 5 6 7 8 9]
Өлшемі: (9,)
Деректер түрі: int64

arr_b:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Өлшемі: (3, 3)
Деректер түрі: int64


In [1]:
import numpy as np

# Кездейсоқ векторлар жасау
vec1 = np.random.randint(1, 11, size=5)  # 1-ден 10-ға дейін
vec2 = np.random.randint(1, 11, size=5)

print("vec1:", vec1)
print("vec2:", vec2)

# Векторлық қосу
sum_vec = vec1 + vec2
print("Қосынды (vec1 + vec2):", sum_vec)

# Әр элементтің квадраты
vec1_sq = vec1 ** 2
print("vec1 элементтерінің квадраты:", vec1_sq)

# Орташа мән
mean_val = vec1.mean()
print("vec1 орташа мәні:", mean_val)

# Ең үлкен элемент
max_val = vec1.max()
print("vec1 ең үлкен мәні:", max_val)


vec1: [ 6  5  8 10  7]
vec2: [8 6 8 7 4]
Қосынды (vec1 + vec2): [14 11 16 17 11]
vec1 элементтерінің квадраты: [ 36  25  64 100  49]
vec1 орташа мәні: 7.2
vec1 ең үлкен мәні: 10
