In [6]:
# Барлық есептер бір ұяшықта
import numpy as np
import torch
import torch.nn as nn

print('='*50)
print('АПТА 15 - БАРЛЫҚ ЕСЕПТЕР')
print('='*50)

# 1-есеп
print('\n1. СВЕРТКА')
I = np.array([[1,2,0,1],[0,1,2,1],[1,0,1,2],[0,1,0,1]])
K = np.array([[1,0],[0,-1]])
result = np.zeros((3,3))
for i in range(3):
    for j in range(3):
        result[i,j] = np.sum(I[i:i+2, j:j+2] * K)
print('Нәтиже:\n', result)

# 2-есеп
print('\n2. ReLU')
relu_in = np.array([[0,0,0],[1,-1,1],[0,0,-1]])
print('ReLU нәтижесі:\n', np.maximum(0, relu_in))

# 3-есеп
print('\n3. MAX POOLING')
F = np.array([[1,3,2,0],[4,6,5,1],[0,2,1,3],[1,0,2,4]])
pool = np.zeros((2,2))
pool[0,0] = np.max(F[0:2,0:2])
pool[0,1] = np.max(F[0:2,2:4])
pool[1,0] = np.max(F[2:4,0:2])
pool[1,1] = np.max(F[2:4,2:4])
print('Нәтиже:\n', pool)

# 4-есеп
print('\n4. DROPOUT')
F = np.array([[2,0],[3,1]])
np.random.seed(42)
mask = np.random.binomial(1, 0.5, size=F.shape)
print('Нәтиже:\n', F * mask / 0.5)

# 5-есеп
print('\n5. BATCH NORMALIZATION')
X = np.array([[1,2,3],[2,3,4],[3,4,5],[4,5,6]])
mu = np.mean(X, axis=0)
var = np.var(X, axis=0)
X_norm = (X - mu) / np.sqrt(var + 0.01)
print('Нәтиже:\n', X_norm)

# 7-есеп
print('\n7. КОМПОЗИТ')
print('28x28 → 26x26 (conv) → 26x26 (ReLU) → 13x13 (pool) → 13x13 (dropout)')
print('Соңғы өлшем: 13x13')

АПТА 15 - БАРЛЫҚ ЕСЕПТЕР

1. СВЕРТКА
Нәтиже:
 [[ 0.  0. -1.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]

2. ReLU
ReLU нәтижесі:
 [[0 0 0]
 [1 0 1]
 [0 0 0]]

3. MAX POOLING
Нәтиже:
 [[6. 5.]
 [2. 4.]]

4. DROPOUT
Нәтиже:
 [[0. 0.]
 [6. 2.]]

5. BATCH NORMALIZATION
Нәтиже:
 [[-1.33630621 -1.33630621 -1.33630621]
 [-0.4454354  -0.4454354  -0.4454354 ]
 [ 0.4454354   0.4454354   0.4454354 ]
 [ 1.33630621  1.33630621  1.33630621]]

7. КОМПОЗИТ
28x28 → 26x26 (conv) → 26x26 (ReLU) → 13x13 (pool) → 13x13 (dropout)
Соңғы өлшем: 13x13
